[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd ../shared && npm install", "npm install"]

[phases.build]
cmds = ["cd ../shared && npm run build || true", "npm run build"]

[start]
cmd = "npm start"

